# ruff: noga: F401
"""substitution autoincrement for rooms_facilities

Revision ID: 4f8ce37dba7f
Revises: 0f5a25b3b07a
Create Date: 2024-10-06 14:25:26.868171

"""
from typing import Sequence, Union

from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "4f8ce37dba7f"
down_revision: Union[str, None] = "0f5a25b3b07a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
